[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "entrypoint"
version = "0.2.0+33"
description = ""
authors = [ "Karl Knechtel <karl.a.knechtel@gmail.com>",]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
entrypoint-update-metadata = "entrypoint.discovery:write_all.invoke"
entrypoint-wrapper = "entrypoint.discovery:make_wrapper_script.invoke"
doc_example_1 = "entrypoint.examples:doc_example_1.invoke"
doc_example_2 = "entrypoint.examples:doc_example_2.invoke"
doc_example_3 = "entrypoint.examples:doc_example_3.invoke"
doc_example_4 = "entrypoint.examples:doc_example_4.invoke"
empty = "entrypoint.examples:empty.invoke"
example = "entrypoint.examples:example.invoke"
renamed = "entrypoint.examples:to_rename.invoke"
renamed_1 = "entrypoint.examples:tricky_1.invoke"
tricky_2 = "entrypoint.examples:tricky_2.invoke"
hard = "entrypoint.examples:hard.invoke"
defaults = "entrypoint.examples:defaults.invoke"
positional_by_keyword = "entrypoint.examples:positional_by_keyword.invoke"
